"""The monthly report model (report_agent/story.py) and its three outputs
(report_agent/render.py), plus the optional AI wording guard."""
from io import BytesIO

import pandas as pd
import pytest
from openpyxl import load_workbook

from report_agent import render
from report_agent.ai_summary import numbers_check, polish
from report_agent.story import build_report
from tests.test_action_center import _book, _prev


@pytest.fixture(scope="module")
def data():
    from helpers import make_df
    df = make_df(_book().to_dict("records"))          # full LCC column set, like a real upload
    return df, _prev(df)


def _headings(model):
    return [b["text"] for b in model["blocks"] if b["type"] == "heading"]


def test_presets_tell_the_same_story_at_different_depths(data):
    c, p = data
    reg = _headings(build_report(c, p, "2026-08", "2026-07", "Regional"))
    lead = _headings(build_report(c, p, "2026-08", "2026-07", "Leadership"))
    assert reg[:3] == lead[:3] == ["Summary", "Scoreboard", "Early Warning: Loans That Slipped"]
    assert "Branches" in reg and "Branches" not in lead            # leaders get the short version
    assert reg[-1] == lead[-1] == "Definitions"


def test_branch_report_needs_one_branch(data):
    c, p = data
    with pytest.raises(ValueError):
        build_report(c, p, "2026-08", "2026-07", "Branch", {"Branch": "All"})
    m = build_report(c[c["Unit"] == "MALEGAON"], p[p["Unit"] == "MALEGAON"], "2026-08", "2026-07", "Branch",
                     {"Branch": "MALEGAON"})
    assert "Executives" in _headings(m) and "Call Lists" in _headings(m)


def test_percent_kpis_change_in_points(data):
    from utils import compute_metrics
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Leadership")
    kpi = next(it for b in m["blocks"] if b["type"] == "kpis" for it in b["items"] if it["label"] == "Delinquency %")
    now, before = compute_metrics(c, p)["Delinquency %"][0], compute_metrics(p, p.iloc[0:0])["Delinquency %"][0]
    assert kpi["value"] == f"{now:.2f}%"
    assert kpi["change"] == f"▲ {now - before:.2f} pts" and kpi["worse"] is True


def test_html_pdf_excel_all_carry_the_same_report(data):
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Regional")
    html = render.to_html(m)
    assert "11 new defaulters" in html and "Generated by CollectionIQ" in html
    assert "Gemini" not in html                                   # AI off by default: no AI credit
    pdf = render.to_pdf(m)
    assert pdf[:4] == b"%PDF" and len(pdf) > 5_000
    wb = load_workbook(BytesIO(render.to_excel(m)))
    assert wb.sheetnames[0] == "Summary"
    assert {"Regions", "Branches", "Definitions"} <= set(wb.sheetnames)
    assert any(name.startswith("Call 1") for name in wb.sheetnames)  # call lists with proof columns


def test_tables_are_complete_in_the_annex_even_when_cut_on_the_page(monkeypatch, data):
    import report_agent.story as story
    monkeypatch.setattr(story, "TABLE_ROWS_ON_PAGE", 1)
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Regional")
    br = next(b for b in m["blocks"] if b["type"] == "table" and b["title"] == "Branches")
    assert len(br["df"]) == 1 and len(br["full"]) == 2 and "Showing the worst 1 of 2" in \
        next(b["note"] for b in m["blocks"] if b["type"] == "heading" and b["text"] == "Branches")


def test_risk_columns_are_shaded_red_never_green(data):
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Regional")
    for b in m["blocks"]:
        if b["type"] != "table":
            continue
        for row in render._cell_colors(b):
            for bg, _ in row:
                assert bg is None or bg.lower() not in ("#16a34a", "#dcfce7", "#f0fdf4")


def test_ai_numbers_must_come_from_the_facts():
    facts = "- 388 new defaulters: 11.9% of last month's STD loans, ₹17.75 Cr SOH."
    assert numbers_check("388 loans fell behind, 11.9% of STD loans.", facts) == []
    assert numbers_check("About 400 loans fell behind.", facts) == ["400"]


def test_ai_paragraph_is_dropped_when_it_invents_a_number(data):
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Leadership")
    good, msg = polish(m, call=lambda prompt: "11 loans that were paid up last month are now behind.")
    assert good and msg.startswith("AI summary added")
    bad, msg = polish(m, call=lambda prompt: "About 9999 loans fell behind.")
    assert bad is None and "9999" in msg
    m["ai_summary"] = good
    assert "AI wording by Gemini" in render.to_html(m)


def test_every_optional_section_builds_and_lands_in_the_annex(data):
    from report_agent.story import OPTIONAL_SECTIONS
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Regional", extras=list(OPTIONAL_SECTIONS))
    base = build_report(c, p, "2026-08", "2026-07", "Regional")
    assert len(m["blocks"]) >= len(base["blocks"])                      # extras only add
    assert _headings(m)[-1] == "Definitions"                            # definitions stay last
    render.to_pdf(m)                                                    # every block renders
    wb = load_workbook(BytesIO(render.to_excel(m)))
    assert len(wb.sheetnames) == len(set(wb.sheetnames))


def test_names_are_escaped_in_html(data):
    c, p = data
    c = c.assign(Unit=c["Unit"].replace("MALEGAON", "R&B <MOTORS>"))
    html = render.to_html(build_report(c, p, "2026-08", "2026-07", "Regional"))
    assert "R&amp;B &lt;MOTORS&gt;" in html and "<MOTORS>" not in html


def test_branch_packs_zip_one_report_per_branch(data):
    import zipfile
    from report_agent.packs import build_branch_packs
    c, p = data
    seen = []
    blob, done = build_branch_packs(c, p, "2026-08", "2026-07", progress=lambda i, n, b: seen.append((i, n, b)))
    names = sorted(zipfile.ZipFile(BytesIO(blob)).namelist())
    assert done == ["BARAMATI", "MALEGAON"] and len(seen) == 2
    assert names == ["BARAMATI_2026-08.pdf", "BARAMATI_2026-08.xlsx", "MALEGAON_2026-08.pdf", "MALEGAON_2026-08.xlsx"]
    blob, _ = build_branch_packs(c, p, "2026-08", "2026-07", with_excel=False)
    assert all(n.endswith(".pdf") for n in zipfile.ZipFile(BytesIO(blob)).namelist())
