"""The monthly report model (report_agent/story.py) and its three outputs
(report_agent/render.py), plus the optional AI wording guard."""
from io import BytesIO

import pandas as pd
import pytest
from openpyxl import load_workbook

from report_agent import render
from report_agent.ai_summary import numbers_check, polish
from report_agent.story import build_report
from tests.test_action_center import _book, _prev


@pytest.fixture(scope="module")
def data():
    from helpers import make_df
    df = make_df(_book().to_dict("records"))          # full LCC column set, like a real upload
    return df, _prev(df)


def _headings(model):
    return [b["text"] for b in model["blocks"] if b["type"] == "heading"]


def test_every_level_opens_with_the_same_story(data):
    c, p = data
    heads = {lv: _headings(build_report(c, p, "2026-08", "2026-07", lv)) for lv in ("Leadership", "Zone", "Regional", "Branch")}
    assert all(h[0] == "At a Glance" for h in heads.values())
    assert "Branches Ranked" in heads["Regional"] and "Branches Ranked" not in heads["Leadership"]   # depth by level
    assert "Who to Call First" in heads["Branch"]
    assert heads["Regional"][-1] == heads["Branch"][-1] == "How to Read This"


def test_glance_tells_good_bad_and_focus_without_repeating(data):
    c, p = data
    g = next(b for b in build_report(c, p, "2026-08", "2026-07", "Regional")["blocks"] if b["type"] == "glance")
    assert g["verdict"]["tone"] in ("good", "bad", "mixed", "info") and g["verdict"]["text"]
    assert 1 <= len(g["good"]) <= 3 and 1 <= len(g["bad"]) <= 3 and len(g["focus"]) <= 3
    assert len(set(g["good"])) == len(g["good"]) and len(set(g["bad"])) == len(g["bad"])
    assert any("new defaulters" in x for x in g["bad"])


def test_percent_kpis_change_in_points(data):
    from utils import compute_metrics
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Leadership")
    kpi = next(it for b in m["blocks"] if b["type"] == "glance" for it in b["tiles"] if it["label"] == "Delinquency")
    now, before = compute_metrics(c, p)["Delinquency %"][0], compute_metrics(p, p.iloc[0:0])["Delinquency %"][0]
    assert kpi["value"] == f"{now:.2f}%"
    assert kpi["change"] == f"▲ {now - before:.2f} pts" and kpi["worse"] is True


def test_html_pdf_excel_all_carry_the_same_report(data):
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Regional")
    html = render.to_html(m)
    assert "11 new defaulters" in html and "WHAT WENT WELL" in html and "Generated by CollectionIQ" in html
    assert "Gemini" not in html                                   # AI off by default: no AI credit
    pdf = render.to_pdf(m)
    assert pdf[:4] == b"%PDF" and len(pdf) > 5_000
    wb = load_workbook(BytesIO(render.to_excel(m)))
    assert wb.sheetnames[0] == "Summary"
    assert {"Branches Ranked", "Roll steps", "Where to focus", "Definitions"} <= set(wb.sheetnames)
    assert any(name.startswith("Call 1") for name in wb.sheetnames)  # call lists with proof columns


def test_long_rankings_show_worst_and_best_on_one_scale_and_all_in_the_annex(monkeypatch, data):
    import report_agent.story as story
    monkeypatch.setattr(story, "BARS_ALL_UP_TO", 1)
    monkeypatch.setattr(story, "BARS_EACH_SIDE", 1)
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Regional")
    worst = next(b for b in m["blocks"] if b["type"] == "bars" and b["title"] == "Needing the most help")
    best = next(b for b in m["blocks"] if b["type"] == "bars" and b["title"] == "Doing best")
    assert len(worst["rows"]) == len(best["rows"]) == 1 and len(worst["full"]) == 2
    assert worst["max"] == best["max"]                               # one scale: the bars compare
    assert "The 1 worst and 1 best of 2" in next(b["note"] for b in m["blocks"]
                                                 if b["type"] == "heading" and b["text"] == "Branches Ranked")


def test_status_is_against_the_reports_own_average(data):
    from report_agent.story import ACT_NOW_GAP_PTS, _status
    assert _status(60.0, 59.0) == "amber" and _status(59.0, 59.0) == "green"
    assert _status(59.0 + ACT_NOW_GAP_PTS, 59.0) == "red" and _status(None, 59.0) is None
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Regional")
    rows = next(b for b in m["blocks"] if b["type"] == "bars" and b["title"] == "Branches Ranked")["rows"]
    assert all(r["status"] in ("red", "amber", "green") for r in rows)
    html = render.to_html(m)
    assert any(word in html for word in ("Act now", "Watch", "On track"))


def test_each_level_makes_one_file_per_unit(data):
    import zipfile
    from report_agent.packs import build_files, units_in, zip_files
    c, p = data
    seen = []
    out = build_files(c, p, "2026-08", "2026-07", "Branch", fmt="PDF", progress=lambda i, n, u: seen.append((i, n, u)))
    names = [n for n, _ in out["files"]]
    assert names == ["branch_BARAMATI_2026-08.pdf", "branch_MALEGAON_2026-08.pdf"] and len(seen) == 2
    assert all(d[:4] == b"%PDF" for _, d in out["files"]) and "At a Glance" in out["preview"]
    assert sorted(zipfile.ZipFile(BytesIO(zip_files(out["files"]))).namelist()) == names
    one = build_files(c[c["Unit"] == "MALEGAON"], p, "2026-08", "2026-07", "Branch", fmt="HTML")
    assert [n for n, _ in one["files"]] == ["branch_MALEGAON_2026-08.html"]     # a branch picked: one file
    lead = build_files(c, p, "2026-08", "2026-07", "Leadership", fmt="Excel")
    assert [n for n, _ in lead["files"]] == ["leadership_report_2026-08.xlsx"] and units_in(c, "Leadership") == []


def test_risk_columns_are_shaded_red_never_green(data):
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Regional")
    for b in m["blocks"]:
        if b["type"] != "table":
            continue
        for row in render._cell_colors(b):
            for bg, _ in row:
                assert bg is None or bg.lower() not in ("#16a34a", "#dcfce7", "#f0fdf4")


def test_ai_numbers_must_come_from_the_facts():
    facts = "- 388 new defaulters: 11.9% of last month's STD loans, ₹17.75 Cr SOH."
    assert numbers_check("388 loans fell behind, 11.9% of STD loans.", facts) == []
    assert numbers_check("About 400 loans fell behind.", facts) == ["400"]


def test_ai_paragraph_is_dropped_when_it_invents_a_number(data):
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Leadership")
    good, msg = polish(m, call=lambda prompt: "11 loans that were paid up last month are now behind.")
    assert good and msg.startswith("AI summary added")
    bad, msg = polish(m, call=lambda prompt: "About 9999 loans fell behind.")
    assert bad is None and "9999" in msg
    m["ai_summary"] = good
    assert "AI wording by Gemini" in render.to_html(m)


def test_every_optional_section_builds_and_lands_in_the_annex(data):
    from report_agent.story import OPTIONAL_SECTIONS
    c, p = data
    m = build_report(c, p, "2026-08", "2026-07", "Regional", extras=list(OPTIONAL_SECTIONS))
    base = build_report(c, p, "2026-08", "2026-07", "Regional")
    assert len(m["blocks"]) >= len(base["blocks"])                      # extras only add
    assert _headings(m)[-1] == "How to Read This"                       # the key to the report stays last
    render.to_pdf(m)                                                    # every block renders
    wb = load_workbook(BytesIO(render.to_excel(m)))
    assert len(wb.sheetnames) == len(set(wb.sheetnames))


def test_names_are_escaped_in_html(data):
    c, p = data
    c = c.assign(Unit=c["Unit"].replace("MALEGAON", "R&B <MOTORS>"))
    html = render.to_html(build_report(c, p, "2026-08", "2026-07", "Regional"))
    assert "R&amp;B &lt;MOTORS&gt;" in html and "<MOTORS>" not in html


def test_every_download_has_a_blue_header_with_white_text():
    from openpyxl import load_workbook as lw
    from ui.components import _excel_bytes
    ws = lw(BytesIO(_excel_bytes.__wrapped__(pd.DataFrame({"A": [1], "B": [2]})))).active
    assert ws["A1"].fill.fgColor.rgb.endswith("1F4E78") and ws["A1"].font.color.rgb.endswith("FFFFFF")


def test_percent_cells_carry_their_count_or_crore():
    row = pd.Series({"NPA%": 12.5, "NPA": 5, "NPA% (SOH)": 8.0, "NPA SOH (Cr)": 1.5})
    assert render.cell_text(row, {"key": "NPA%", "fmt": "pct", "count": "NPA"}) == "12.5% (5)"
    assert render.cell_text(row, {"key": "NPA% (SOH)", "fmt": "pct", "amount": "NPA SOH (Cr)"}) == "8.0% (₹1.50 Cr)"


def test_section_keys_never_clash():
    # A main section sharing a key with an optional one would pull both in.
    from report_agent.story import MAIN_SECTIONS, OPTIONAL_SECTIONS, PRESET_SECTIONS
    assert not set(MAIN_SECTIONS) & set(OPTIONAL_SECTIONS)
    assert all(set(v) <= set(MAIN_SECTIONS) for v in PRESET_SECTIONS.values())


def test_only_the_picked_units_get_a_file(data):
    from report_agent.packs import build_files
    c, p = data
    one = build_files(c, p, "2026-08", "2026-07", "Branch", fmt="HTML", only=["MALEGAON"])
    assert [n for n, _ in one["files"]] == ["branch_MALEGAON_2026-08.html"]
    none = build_files(c, p, "2026-08", "2026-07", "Branch", fmt="HTML", only=[])
    assert none["files"] == []                       # nothing picked: no files, never the whole book
